config/routes.rb
Rails.application.routes.draw do
  resources :educational_institutions
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/educational_institution.rb
class EducationalInstitution < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:rut, :institution, :region, :city, :state, :adress, :email, :phone)
    end
end

app/controllers/educational_institutions_controller.rb
class EducationalInstitutionsController < ApplicationController
  before_action :set_educational_institution, only: [:show, :edit, :update, :destroy]

  # GET /educational_institutions
  # GET /educational_institutions.json
  def index
    @educational_institutions = EducationalInstitution.all
  end

  # GET /educational_institutions/1
  # GET /educational_institutions/1.json
  def show
  end

  # GET /educational_institutions/new
  def new
    @educational_institution = EducationalInstitution.new
  end

  # GET /educational_institutions/1/edit
  def edit
  end

  # POST /educational_institutions
  # POST /educational_institutions.json
  def create
    @educational_institution = EducationalInstitution.new(educational_institution_params)

    respond_to do |format|
      if @educational_institution.save
        format.html { redirect_to @educational_institution, notice: 'Educational institution was successfully created.' }
        format.json { render :show, status: :created, location: @educational_institution }
      else
        format.html { render :new }
        format.json { render json: @educational_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educational_institutions/1
  # PATCH/PUT /educational_institutions/1.json
  def update
    respond_to do |format|
      if @educational_institution.update(educational_institution_params)
        format.html { redirect_to @educational_institution, notice: 'Educational institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @educational_institution }
      else
        format.html { render :edit }
        format.json { render json: @educational_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educational_institutions/1
  # DELETE /educational_institutions/1.json
  def destroy
    @educational_institution.destroy
    respond_to do |format|
      format.html { redirect_to educational_institutions_url, notice: 'Educational institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_educational_institution
      @educational_institution = EducationalInstitution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def educational_institution_params
      params.require(:educational_institution).permit(:rol_data_base, :Name, :Type, :Integration, :region, :city, :state, :adress, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/educational_institutions_helper.rb
module EducationalInstitutionsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rut %>
    <%= form.number_field :rut %>
  </div>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Rut</th>
      <th>Institution</th>
      <th>Region</th>
      <th>City</th>
      <th>State</th>
      <th>Adress</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.rut %></td>
        <td><%= client.institution %></td>
        <td><%= client.region %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.adress %></td>
        <td><%= client.email %></td>
        <td><%= client.phone %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut:</strong>
  <%= @client.rut %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @client.institution %>
</p>

<p>
  <strong>Region:</strong>
  <%= @client.region %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @client.adress %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/educational_institutions/_form.html.erb
<%= form_with(model: educational_institution, local: true) do |form| %>
  <% if educational_institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(educational_institution.errors.count, "error") %> prohibited this educational_institution from being saved:</h2>

      <ul>
      <% educational_institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rol_data_base %>
    <%= form.number_field :rol_data_base %>
  </div>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Type %>
    <%= form.text_field :Type %>
  </div>

  <div class="field">
    <%= form.label :Integration %>
    <%= form.check_box :Integration %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/educational_institutions/edit.html.erb
<h1>Editing Educational Institution</h1>

<%= render 'form', educational_institution: @educational_institution %>

<%= link_to 'Show', @educational_institution %> |
<%= link_to 'Back', educational_institutions_path %>

app/views/educational_institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Educational Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Rol data base</th>
      <th>Name</th>
      <th>Type</th>
      <th>Integration</th>
      <th>Region</th>
      <th>City</th>
      <th>State</th>
      <th>Adress</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educational_institutions.each do |educational_institution| %>
      <tr>
        <td><%= educational_institution.rol_data_base %></td>
        <td><%= educational_institution.Name %></td>
        <td><%= educational_institution.Type %></td>
        <td><%= educational_institution.Integration %></td>
        <td><%= educational_institution.region %></td>
        <td><%= educational_institution.city %></td>
        <td><%= educational_institution.state %></td>
        <td><%= educational_institution.adress %></td>
        <td><%= educational_institution.phone %></td>
        <td><%= educational_institution.email %></td>
        <td><%= link_to 'Show', educational_institution %></td>
        <td><%= link_to 'Edit', edit_educational_institution_path(educational_institution) %></td>
        <td><%= link_to 'Destroy', educational_institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Educational Institution', new_educational_institution_path %>

app/views/educational_institutions/new.html.erb
<h1>New Educational Institution</h1>

<%= render 'form', educational_institution: @educational_institution %>

<%= link_to 'Back', educational_institutions_path %>

app/views/educational_institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rol data base:</strong>
  <%= @educational_institution.rol_data_base %>
</p>

<p>
  <strong>Name:</strong>
  <%= @educational_institution.Name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @educational_institution.Type %>
</p>

<p>
  <strong>Integration:</strong>
  <%= @educational_institution.Integration %>
</p>

<p>
  <strong>Region:</strong>
  <%= @educational_institution.region %>
</p>

<p>
  <strong>City:</strong>
  <%= @educational_institution.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @educational_institution.state %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @educational_institution.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @educational_institution.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @educational_institution.email %>
</p>

<%= link_to 'Edit', edit_educational_institution_path(@educational_institution) %> |
<%= link_to 'Back', educational_institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProyect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>